##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

## Note: Any command which fails in any stage below result in the command stopping, and endStage being run.
## A flow file can have one or more stages, each with multiple "actions", 
## or your flow file can have multiple stages with fewer actions in each stage.
globalVariables:
  TAG: "0.0"
  ENV: DEV
  CHECK_DRIFT: true
  SCHEMAS: "CAPS"
  
stages:

  Drift-Detection:
    # Check if manual updates were made to the environment since last deployment
    actions:
      - type: shell
        if: "${CHECK_DRIFT} == true && exists('snapshots/DEV-snapshot.json')"
        command: liquibase --include-relations-for-computed-columns=true diff --reference-url=offline:oracle?snapshot=${ENV}-snapshot.json --report-name="drift-report-${ENV}.html" --reports-enabled=true --drift-severity=0 --schemas=${SCHEMAS} --diff-types="catalogs, checkconstraints, columns, databasepackage, databasepackagebody, foreignkeys, functions, indexes, primarykeys, storedprocedures, tables, triggers, uniqueconstraints, views"

## The endStage ALWAYS RUNS. 
## So put actions here which you desire to perform whether previous stages' actions succeed or fail.
## If you do not want any actions to ALWAYS RUN, simply delete the endStage from your flow file.

endStage:
  actions:
    - type: liquibase
      command: history
      
    - type: liquibase
      command: snapshot
      cmdArgs: { snapshot-format: json, schemas: "${SCHEMAS}"}
      globalArgs: { output-file: 'snapshots/${ENV}-snapshot.json' }