# liquibase.licenseKey: <SET AS ENVIRONMENT VARIABLE LIQUIBASE_LICENSE_KEY>

searchPath=flows,checks,changelogs
changeLogFile=rootchangelog.yaml

#### Database Settings ####
liquibase.command.url=jdbc:oracle:thin:@<hostname>:<port>/<db_name>
liquibase.command.username: <SET AS ENVIRONMENT VARIABLE LIQUIBASE_COMMAND_USERNAME>
liquibase.command.password: <SET AS ENVIRONMENT VARIABLE LIQUIBASE_COMMAND_PASSWORD>
liquibase.liquibaseSchemaName: LIQUIBASE

#### Logging Settings ####
### Valid values, from least amount of logging to most, are: ###
### OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL                ###            
logLevel: INFO
liquibase.logFormat=JSON_PRETTY
liquibase.logFile=logs/log.json
liquibase.showBanner: false

#### Checks Settings ####
checks-scripts-enabled=true
liquibase.command.checks.run.autoUpdate=off

#### Flow Settings ####
liquibase.command.flowFile=liquibase-build.flowfile.yaml

#### Reports Settings ####
liquibase.reports.enabled=true
liquibase.reports.path=reports

#### History Settings ####
liquibase.dbclhistory.enabled=true

#### SqlPlus Settings ####
liquibase.sqlplus.createSpool=true
liquibase.sqlplus.keep.temp.path=./reports