# liquibase.licenseKey: <SET AS ENVIRONMENT VARIABLE LIQUIBASE_LICENSE_KEY>

changeLogFile=changelogs/changelog.xml

#### Database Settings ####
liquibase.command.url=jdbc:oracle:thin:@<hostname>:<port>/<db_name>
liquibase.command.username: <SET AS ENVIRONMENT VARIABLE LIQUIBASE_COMMAND_USERNAME>
liquibase.command.password: <SET AS ENVIRONMENT VARIABLE LIQUIBASE_COMMAND_PASSWORD>
liquibase.liquibaseSchemaName: LIQUIBASE

#### Logging Settings ####
### Valid values, from least amount of logging to most, are: ###
### OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL                ###            
logLevel: INFO
liquibase.logFormat=JSON_PRETTY
liquibase.logFile=logs/log.json
liquibase.showBanner: false

#### Checks Settings ####
#liquibase.command.checks.run.checksSettingsFile=checks/liquibase.checks-settings.conf
#liquibase.command.checks.show.checksSettingsFile=checks/liquibase.checks-settings.conf
checks-scripts-enabled=true
liquibase.command.checks.run.autoUpdate=off

#### Flow Settings ####
liquibase.command.flowFile=flows/liquibase.flowfile.yaml

#### Reports Settings ####
liquibase.reports.enabled=true
liquibase.reports.path=reports

#### History Settings ####
liquibase.dbclhistory.enabled=true