CREATE TABLE cars (
    car_id        NUMBER GENERATED BY DEFAULT AS IDENTITY
                  CONSTRAINT pk_cars PRIMARY KEY,
    make          VARCHAR2(50)  NOT NULL,
    model         VARCHAR2(50)  NOT NULL,
    model_year    NUMBER(4)
                  CONSTRAINT chk_cars_model_year
                  CHECK (model_year BETWEEN 1886 AND 2100),
    color         VARCHAR2(30),
    body_type     VARCHAR2(30),
    mileage       NUMBER(10)
                  CONSTRAINT chk_cars_mileage
                  CHECK (mileage >= 0),
    vin           VARCHAR2(17)
                  CONSTRAINT uk_cars_vin UNIQUE,
    price         NUMBER(10,2),
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);