-- liquibase formatted sql

-- changeset asmith:01
CREATE TABLE AUTOMOBILES01 (CARID NUMBER(*, 0), MAKE VARCHAR2(255 BYTE), MODEL VARCHAR2(255 BYTE));
--rollback DROP TABLE AUTOMOBILES01

-- changeset asmith:02
CREATE TABLE AUTOMOBILES02 (CARID NUMBER(*, 0), MAKE VARCHAR2(255 BYTE), MODEL VARCHAR2(255 BYTE));
--rollback DROP TABLE AUTOMOBILES02