# .github/workflows/setup-liquibase/action.yml
name: 'Setup Liquibase Environment'
description: 'Sets up Java, Liquibase Pro, and AWS extension'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Liquibase Pro
      uses: liquibase/setup-liquibase@v1
      with:
        version: '4.33.0'
        edition: 'pro'
