# .github/workflows/setup-liquibase/action.yml
name: 'Setup Liquibase Environment'
description: 'Sets up Java and Liquibase Secure'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@v5.2.0
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Liquibase Secure
      uses: liquibase/setup-liquibase@v3
      with:
        version: '5.2.2'
        edition: 'secure'
