##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  BUCKET: ${AWS_S3_BUCKET}
  SCHEMAS: ${LB_SCHEMAS}

stages:
  GenerateChangeLog:
    actions:
      - type: liquibase
        command: generate-changelog
        cmdArgs: { changelog-file: 's3://${BUCKET}/oracleChangelogs/${ENV}-changelog.oracle.sql', overwrite-output-file: "true", schemas: "${SCHEMAS}" }

      - type: liquibase
        command: generate-changelog
        cmdArgs: { changelog-file: 'generatechangelogs/oracleChangelogs/${ENV}-changelog.oracle.sql', overwrite-output-file: "true", schemas: "${SCHEMAS}" }
        
      - type: shell
        command: echo 'Generate Changelog saved to s3://${BUCKET}/oracleChangelogs/${ENV}-changelog.oracle.sql'