##########           LIQUIBASE DRIFT FLOWFILE                ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  BUCKET: ${AWS_S3_BUCKET}
  SCHEMAS: ${LB_SCHEMAS}

stages:

  Drift-Detection:
    # Check if manual updates were made to the environment since last deployment
    actions:
    - type: shell
      command: liquibase --search-path=s3://${BUCKET}/oracleSnapshots/ diff --reference-url=offline:oracle?snapshot=${ENV}-snapshot.json --report-name="drift-report-${ENV}.html" --reports-enabled=true --drift-severity=1 --schemas=${SCHEMAS}