##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########

globalVariables:
  ENV: ${ENVIRONMENT}
  BUCKET: ${AWS_S3_BUCKET}
  SCHEMAS: ${LB_SCHEMAS}
  UTILITY: ${LB_UTILITY}

stages:
  Utility:
    actions:
    
      - type: shell
        command: echo 'Running ${UTILITY}'    
    
      - type: liquibase
        if: "${UTILITY} == changelog-sync"
        command: changelog-sync
        
      - type: shell
        if: "${UTILITY} == generate-changelog"
        command: echo 'Generate Changelog saved to s3://${BUCKET}/oracleChangelogs/${ENV}-changelog.oracle.xml'

      - type: liquibase
        if: "${UTILITY} == generate-changelog"
        command: generate-changelog
        cmdArgs: { changelog-file: 's3://${BUCKET}/oracleChangelogs/${ENV}-changelog.oracle.xml', overwrite-output-file: "true", schemas: "${SCHEMAS}" }
        
      - type: shell
        if: "${UTILITY} == generate-changelog"
        command: echo 'Generate Changelog saved to s3://${BUCKET}/oracleChangelogs/${ENV}-changelog.oracle.xml'

      - type: liquibase
        if: "${UTILITY} == release-locks"
        command: release-locks

      - type: liquibase
        if: "${UTILITY} == snapshot"
        command: snapshot
        cmdArgs: {  snapshot-format: json, schemas: "${SCHEMAS}"}
        globalArgs: { output-file: 's3://${BUCKET}/oracleSnapshots/${ENV}-snapshot.json' }
        
      - type: shell
        if: "${UTILITY} == snapshot"
        command: echo 'Snapshot saved to s3://${BUCKET}/oracleSnapshots/${ENV}-snapshot.json'