# validate-changes-update-db.yaml
# Author: Pete Pickerill
# Description:
#   This flow runs several Liquibase commands to generate information that could be usefil for review, auditing
#   and troubleshooting purposes.  It will run in all shared pipeline environments from CI onward. It is not
#   required in development environments

stages:
  validateChangelog:
  # Run validate on Repo Changelog
    actions:
    - type: liquibase
      command: validate
      cmdArgs: {}

  # Run Checks on Repo Changelog
    - type: liquibase
      command: checks run
      cmdArgs: {}
  
  generateUpdateInfo:
    actions:
    - type: liquibase
      # Run everywhere but DEV
      if: "${LIQUIBASE_FLOW_ENV} != dev"
      command: flow
      cmdArgs: {flow-file: "${LIQUIBASE_FLOW_DIR}/generate-update-info.yaml"}


  liquibaseUpdate:
  # Run Update on Latest Repo State
    actions:
    - type: liquibase
      command: update
      cmdArgs: {}

  databaseChecks:
  # Run database checks on post update state
    actions:
    - type: liquibase
      command: checks run
      cmdArgs: {checks-scope: "database"}