#############################################################################
#  GitHub Action to perform drift detection using Liquibase Secure.
#  
##############################################################################
name: 'Liquibase Secure Drift Detection'
run-name: ${{ github.event.inputs.environment }} drift of current repo by ${{ github.actor }}

on:
  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:
    
      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment for drift detection'
        type: environment
        required: true
        default: DEV

####################################################################
#  Set up the environment
#####################################################################
env:
  # AWS S3 bucket is the host part of the S3 bucket
  AWS_S3_BUCKET: ${{ vars.AWS_S3_BUCKET }}
  
  # AWS Access credentials use by the Liquibase Pro S3 Extension
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  
  # Secure License key
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_LICENSE_KEY }}
  
  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ vars.LIQUIBASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.LIQUIBASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.LIQUIBASE_PASSWORD }}

  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: MUREX
  
  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: MUREX
  LIQUIBASE_COMMAND_REFERENCE_DEFAULT_SCHEMA_NAME: MUREX

  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: flows,checks,changelogs,snapshots
  
  # The database changelog. See https://docs.liquibase.com/concepts/changelogs/working-with-changelogs.html
  LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog.xml
  
  ENVIRONMENT: ${{ inputs.environment }}

  # Reports
  LIQUIBASE_REPORT_PATH: reports
  
  # Values: OFF, SEVERE, WARNING, INFO, FINE
  LIQUIBASE_LOG_LEVEL: INFO
  LIQUIBASE_LOG_FORMAT: JSON_PRETTY
  LIQUIBASE_LOG_FILE: logs/log.json
  
  # Drift Detection
  LB_SCHEMAS: "MUREX"
  
  # History Table
  LIQUIBASE_DBCLHISTORY_ENABLED: true

jobs:
  #########################################################################
  #  Drift
  #########################################################################

  database-build:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Liquibase Environment
      uses: ./.github/workflows/setup-liquibase

    - name: Liquibase Drift Detection Flow
      run: liquibase flow --flow-file=liquibase-drift.flowfile.yaml

    - name: Upload Reports Artifact
      if: always()
      uses: ./.github/workflows/upload-reports
      with:
        job-type: deploy
        upload-other: false
