#############################################################################
#  GitHub Action to perform a rollback for selected environment.
##############################################################################
name: 'Rollback Liquibase - LBP'
permissions:
  contents: write  
  actions: read

run-name: ${{ inputs.environment}} rollback of current repo by ${{ github.actor }}

on:

  workflow_dispatch:
    # Following are the inputs received via the GitHubActions Run workflow dialog
    inputs:

      # The type 'environment' will automatically pull in the environments created in GitHub
      environment:
        description: 'Environment for rollback'
        type: environment
        required: true
        default: QA

      lb_tag:
        description: 'Tag for rollback'
        type: string
        required: true

####################################################################
#  Set up the environment
#####################################################################
env:

  # Pro License key
  # See https://docs.liquibase.com/workflows/liquibase-pro/how-to-apply-your-liquibase-pro-license-key.html
  LIQUIBASE_LICENSE_KEY: ${{ secrets.LIQUIBASE_PRO_LICENSE_KEY }} 

  # JDBC URL of the database per environment
  # See https://docs.liquibase.com/workflows/liquibase-community/using-jdbc-url-in-liquibase.html
  LIQUIBASE_COMMAND_URL: ${{ vars.DATABASE_URL }}

  # Credentials for the environment's database https://docs.liquibase.com/parameters/command-parameters.html
  LIQUIBASE_COMMAND_USERNAME: ${{ secrets.DATABASE_USERNAME }}
  LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}

  # Liquibase schema: Specified to allow flexibility in storage of Liquibase Change Tracking Tables
  # See https://docs.liquibase.com/parameters/liquibase-schema-name.html
  LIQUIBASE_LIQUIBASE_SCHEMA_NAME: "MUREX"

  # Default schema: Specify schema for all changes
  LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: "MUREX"
  # LIQUIBASE_COMMAND_REFERENCE_DEFAULT_SCHEMA_NAME: Sales

  # Search path (See https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html)
  LIQUIBASE_SEARCH_PATH: liquibase-files, liquibase, snapshots

  # The database changelog. See https://docs.liquibase.com/concepts/changelogs/working-with-changelogs.html
  LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog.xml

  ENVIRONMENT: ${{ inputs.environment }}
  BRANCH: ${{ github.ref_name }}
  LB_TAG: ${{ inputs.lb_tag }}

  LIQUIBASE_REPORT_PATH: reports
  # Values: OFF, SEVERE, WARNING, INFO, FINE
  LIQUIBASE_LOG_LEVEL: INFO
  LIQUIBASE_LOG_FORMAT: JSON_PRETTY
  LIQUIBASE_LOG_FILE: logs/log.json

  LB_SCHEMAS: "MUREX"
  LIQUIBASE_DBCLHISTORY_ENABLED: true

jobs:
  #########################################################################
  #  Build
  #########################################################################

  database-build:
    runs-on: [self-hosted]
    environment: ${{ inputs.environment }}
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Required for self-hosted runners
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - uses: liquibase/setup-liquibase@v1
      with:
        version: '4.33.0'
        edition: 'pro'

    - name: Liquibase Rollback Flow
      run: |
        liquibase flow --flow-file=liquibase-rollback.flowfile.yaml